### PR TITLE
Update three.js to r59

### PR DESCRIPTION
**Pull request by TiagoCavalcanteTrindade**
On migration guide of three.js there's no mention of changes in `CubeGeometry`, in r60 `CubeGeometry` uses triangles to be drew, not squares, leading to weird result. So I opted to update just to r59 by now.

The result without change the code of r60 of the bounding box:
image

### CODE REVIEW

**Comment by rocky** [comment]
@TiagoCavalcanteTrindade  Thanks for doing this! 

Let's wait until CI clears and then we can pull.

Would you like write access to this repository so you can commit branches directly here?

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky yes, I'd like to have write access.

Thanks 😄!

**Comment by rocky** [comment]
> @rocky yes, I'd like to have write access.
> 
> Thanks !

You should have an invite now.  BTW https://hub.docker.com/repository/docker/mathicsorg/mathics is a docker container that now threejs r54 and the ticksStyle changes.  I generally update docker containers once a week with the latest goodies.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky I'll look at the [docker image](https://github.com/Mathics3/mathics-omnibus).

I can [try to] update it latter this week.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky for the next contributions should I create and merge PRs or just push to master?

**Comment by rocky** [comment]
What we typically do is 

* create a branch in this repository and commit to the new branch.
* Make sure CI passes.
* have the branch reviewed by someone else. 
* let that person merge, or get the go ahead from the person. 

However sometimes others will disappear. So if you don't hear back in a couple of days on a PR and CI passes and you feel this should go into master, then merge it yourself. 

I am looking at `Graphics3D[Polygon[{{-2, -2, 0}, {2, 2, 0}, {1, 0, 2}, {4, -3, 0}}]]` and don't see the Z value respected. I wonder if this is a problem in Mathics core or on this side.

**Comment by TiagoCavalcanteTrindade** [comment]
> @TiagoCavalcanteTrindade What we typically do is
> 
> * create a branch in this repository and commit to the new branch.
> * Make sure CI passes.
> * have the branch reviewed by someone else.
> * let that person merge, or get the go ahead from the person.
> 
> However sometimes others will disappear. So if you don't hear back in a couple of days on a PR and CI passes and you feel this should go into master, then merge it yourself.

Ok, I'll do that.

> I am looking at `Graphics3D[Polygon[{{-2, -2, 0}, {2, 2, 0}, {1, 0, 2}, {4, -3, 0}}]]` and don't see the Z value respected. I wonder if this is a problem in Mathics core or on this side.

This is my output:
image
By my eyes this looks right, but if there's an error it should be on this side (I console logged the coordinates and they're right).

**Comment by rocky** [comment]
Note there is no shading whee you can see edges. Exaggerate the z dimension and spin around: 

```
Graphics3D[Polygon[{{-2, -2, 0}, {2, 2, 0}, {1, 0, 2}, {4, -3, 0}}]]
```

The bounding box gets wider but the image doesn't start to fill that in. 

It might be just my browser Firefox though...

**Comment by rocky** [comment]
(BTW for 2D our SVG polygon handling seems to make things concave always.)

**Comment by rocky** [comment]
@TiagoCavalcanteTrindade Do you have a suite of test cases that you run to check that things are okay? If not, we should put something together and save that in a worksheet. 

See "Saving, Loading, Deleting Worksheets" around page 26 and "about' on page 25 to see where the information is saved.

**Comment by TiagoCavalcanteTrindade** [comment]
> @TiagoCavalcanteTrindade Do you have a suite of test cases that you run to check that things are okay? If not, we should put something together and save that in a worksheet.

@rocky yes, this is the following:
```
Graphics3D[{
    {Green,  Cuboid[{-.5, -.5, 0}]},
    {Orange, Line[{{-1, -1, 0}, {1,1,0}}]}
}]

Graphics3D[Sphere[], Axes->True]

Graphics3D[Sphere[], Axes->True, TicksStyle->{Red,Green,Blue}]

Graphics3D[{Orange, Point[Table[{Sin[t], Cos[t], 0}, {t, 0, 2 Pi, Pi / 15.}]]}]

Graphics3D[{Blue, Polygon[{{-.25,-.25,0}, {.25,.25,0}, {-.25,.25,0}}]}]

Graphics3D[{Green, Polygon[{{0,0,0}, {1,0,0}, {1,1,0}, {.5,1.5,0}, {0,0,0}}]}]
```

This is what happens when I turn around:
polygon

**Comment by rocky** [comment]
This looks wrong because the polygon is in one plane and it should be be. The Z values vary.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky now I understood you, I guess this is because of three.js shape is 2d, I'll try do let this right.

**Comment by rocky** [comment]
@TiagoCavalcanteTrindade  If you pull down the latest change to mathics-omnibus
https://github.com/Mathics3/mathics-omnibus/commit/6e4b21d25149550e06ffecebad055091ff7994b8

I have added all the the test cases to a worksheet called "3D Graphics Test Suite" into the Sqlite database. 

To be able to access this run the Django server like this: 

```
 MATHICS_DJANGO_DB_PATH=.../mathics-omnibus/docker/django-db/mathics.sqlite  python mathics_django/manage.py runserver
```

Where `...` you fill in where the SQLite file is located on your disk. 

If you add or change examples and save, it will go back into SQLite.

**Pull request merged**
