### PR TITLE
Include quotes when top-level output is a string

### PR DESCRIPTION
**Pull request by rocky**
A small change that I've been thinking about.  I am interested in your thoughts though....

In Mathics 2.0 or so strings were formatted in MathML mode which put them in Sans Serif (usually).  

Previously I changed this so this is no longer in MathML mode and so now strings and symbols are visually more distinct. 
The fact that this is not centered was an artifact that I don't care one about one way or another, but I suspect people would prefer to have this centered like everything else. Your thoughts? 

BTW we probably should separate the cell so that "In" and "Out" are more separate. 

I understand that Mathematica strips off the quotes. I find this annoying not only because you can't tell symbols from strings, but also if you cut and paste the output, you can't use it as input without adding back in the quotes.

But again, I am curious in your views as to how to improve this.

### CODE REVIEW

**Comment by TiagoCavalcanteTrindade** [comment]
> Previously I changed this so this is no longer in MathML mode and so now strings and symbols are visually more distinct.

I think they should be.

> The fact that this is not centered was an artifact that I don't care one about one way or another, but I suspect people would prefer to have this centered like everything else. Your thoughts?

I think we shouldn't alienate to Mathematica, but I googled it and Mathematica doesn't center the strings. Also UX isn't my best.

> BTW we probably should separate the cell so that "In" and "Out" are more separate.

Yes, the options we have are:
- add more space, I think this isn't the best idea;
- add a `<hr />`, I think this doesn't looks good;
- instead of a border in the whole cell, a border around the input and other around the output, I think this would be confusing as differently from mathicsscript, Mathics Django doesn't have the `In`s and `Out`s;
- add two borders around the input and output, I think this is too much information for the eyes;
- add a border around the output;
- add a border around the input, this is what Jupyter notebooks do, so I think it's the best.

---

Also, about transfer Mathics Core, I think that if we do it, we should transfer the other repositories too.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky what do you and @mmatera think?  
(I said a border around the input was the best, but now I think a border around the output is the best.

image

**Comment by rocky** [comment]
My sense of UI is also something not to be trusted. So I recommend (and it is a general recommendation) to follow the way something else does it. In particular follow Jupyter  because even if it isn't optimum from some hypothetical UI designer sense, at least it will be consistent with similar kinds of things and hopefully not confusing for people.

And down the line we'll be moving to Jupyter too. (But like so many other things, best first to get things cleaned up in the environment we currently have.)

**Comment by rocky** [comment]
I should also note that the example you have is not something we'll ever see. Right now the decision is on a _top-level_ entity.

There is the larger issue of handling strings _whereever_ they appear in the output, but that is part of a larger problem and discussion of the whole output formatting revamp and this is its own separate mess. So for now I limit things to just this somewhat special case.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky here how Jupyter does.

image
(for me this doesn't looks good)

I also added some color to strings and centered them.

I'll push my modifications and then you can test with other queries.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky I was thinking if we should keep the quotes and then I queried the following:
image

Now I think that we really should keep the quotes, as we have an function which strip them out.

**Comment by TiagoCavalcanteTrindade** [comment]
Also, this fixes the bug mentioned [here](https://github.com/Mathics3/mathics-django/pull/77#issuecomment-860900134).

**Comment by rocky** [comment]
LGTM - but please I'd rather many smaller commits than one combining a number of things together. If something goes wrong it is easier to pinpoint and isolate. 

(I will confess that I and @mmatera and probably others have a habit of piggybacking separate kinds of changes. Let's face it, it is easier to do if you are short on time. And the code needs soooo many changes.)

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky ok, I'll start doing that.

> If something goes wrong it is easier to pinpoint and isolate.

Yes, also much easier to visualizate the diffs, sometimes I exagerate in squashing the things up.

**Comment by rocky** [comment]
So now I learn that with this commit I can't retrieve saved worksheets. 

Try saving http://localhost:8000/#cXVlcmllcz0oKiUyMEFkYXB0ZWQlMjBmcm9tJTNBJTIwaHR0cHMlM0ElMkYlMkZ3d3cud29sZnJhbS5jb20lMkZsYW5ndWFnZSUyRmVsZW1lbnRhcnktaW50cm9kdWN0aW9uJTJGMm5kLWVkJTJGMDEtc3RhcnRpbmctb3V0LWVsZW1lbnRhcnktYXJpdGhtZXRpYy5odG1sJTIwKikmcXVlcmllcz0oKiUyMEFkZCUyMG51bWJlcnMlMjAqKSZxdWVyaWVzPTIlMjAlMkIlMjAyJnF1ZXJpZXM9KColMjBNdWx0aXBseSUyMG51bWJlcnMlMjAqKSZxdWVyaWVzPTEyMzQlMjAlMkIlMjA1Njc4JnF1ZXJpZXM9MTIzNCo1Njc4JnF1ZXJpZXM9MSUyMCUyQiUyMDIlMjAlMkIlMjAzJnF1ZXJpZXM9MSUyMDIlMjAzJTIwNCUyMDUmcXVlcmllcz01JTIwJTVFJTIwMiZxdWVyaWVzPTMlMjAlNUUlMjAoNyUyMDgpJnF1ZXJpZXM9KDQlMjAtJTIwMikqKDMlMjAlMkIlMjA0KSZxdWVyaWVzPSgyOSUyMDEwJTVFMyklMjA3MyZxdWVyaWVzPUFwcGx5JTVCUGx1cyUyQyUyMFJhbmdlJTVCLTMlMkMlMjAzJTVEJTVEJnF1ZXJpZXM9MSUyRjA=

Then see if you can load back in the results.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky no, also isn't working to me. I'll look at that.

**Comment by rocky** [comment]
If there is a better way to save and load worksheets that is fine too. All of this is real hacky. Useful (if you work around the hackiness), but still hacky.

**Comment by rocky** [comment]
Another thing I an now noticing is that the the output box constrains MathJaX's zoom so that it now pops up with horizontal and vertical scrollbars for a too small window.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky I'll also look at that, but today I'm a bit busy. Tomorrow I'll have time.

**Pull request merged**
