### PR TITLE
Misc documentation fixes

### PR DESCRIPTION
**Pull request by rocky**
Module location mathics.doc.doc -> mathics.doc.common_doc
Don't add to online doc sections which are empty

### CODE REVIEW

**Comment by rocky** [comment]
Note: if/when this clears, I'll be merging this. Of course after the fact you can review. I want to get out another docker image this week.

And then hopefully next week we will be in shape for a release of everything.

**Review by TiagoCavalcanteTrindade — APPROVED** [review]
LGTM - I'll look at the `RowBox`.

**Comment by rocky** [comment]
> LGTM - I'll look at the `RowBox`.

Do you mean here or in Mathics core?  Or at for which aspect? (Recall as I have been maintaining, there are generally multiple bugs all over the place and it is too difficult for me to try to fix all of them at once). 

I should mention that I fully expect more rounds of refactoring as we start to get all of this under control. Just like we have been doing for formatting (which is still far from complete). 

One thing that I expect will happen in the future is that the boxing routines will change various default parameters like the default image size from normal to small.  This will help in the display of various images that appear in lists.

But all of that is not for this weekend.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky I said that because of the FIXME that says `RowBox` have documentation, but it isn't appearing.

**Comment by rocky** [comment]
@TiagoCavalcanteTrindade Ok thanks. The simple thought I had was to add a class variable like 

```
class RowBox()
   user_documentation = True # or False
```

and have this take precedence over whether there is "Box" at the end. (If this class variable doesn't exist, then we default to not showing the docstring as we have now.).

**Pull request merged**
