### PR TITLE
Surround Strings in quotes

### PR DESCRIPTION
**Pull request by rocky**
Your thoughts? 

Feel free to comment, change, close, or commit.

### CODE REVIEW

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky the backend should decide if show or not the quotes, if the frontend do it weird things can happen as 2 double quotes showing, or you ask to print quotes and they don't get printed, so I decided to fix the `FIXME` of `format.py` line 82, I just have one problem: how do I get the arguments in the function `format_output`?

**Comment by rocky** [comment]
> @rocky the backend should decide if show or not the quotes. If the frontend do it weird things can happen as 2 double quotes or none when one should appear.
> 
> So I decided to do [this FIXME](https://github.com/Mathics3/mathics-django/blob/b0e4c248e36966a7915e0e89805681eb5f80b46b/mathics_django/web/format.py#L82-L84). I just have one problem: how do I discover if `--wl-strict-wl-ouput` was set inside the `format_output` function?

You'd add this as a setting in https://github.com/Mathics3/mathics-django/blob/master/mathics_django/autoload/settings.m

and using an evaluation object run something like:

```
        query = evaluation.parse("Settings`QuoteStrings")
        quote_strings = query.evaluate(evaluation).to_python()
```

Getting the evaluation thing, I haven't worked out in detail though.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky I made the following:
```py
definitions = None
evaluation = Evaluation(definitions)
query = evaluation.parse("Settings`QuotedStrings")
quoted_strings = query.evaluate(evaluation).to_python()
print(quoted_strings)
```

And the following:
```py
definitions = Definitions()
evaluation = Evaluation(definitions)
query = evaluation.parse("Settings`QuotedStrings")
quoted_strings = query.evaluate(evaluation).to_python()
print(quoted_strings)
```

But the result was always ``Settings`QuotedStrings``.

**Comment by rocky** [comment]
> @rocky I made the following:
> 
> ```python
> definitions = None
> evaluation = Evaluation(definitions)
> query = evaluation.parse("Settings`QuotedStrings")
> quoted_strings = query.evaluate(evaluation).to_python()
> print(quoted_strings)
> ```
> 
> And the following:
> 
> ```python
> definitions = Definitions()

This starts out with empty definitions.  I think you want to use the same definitions that are in use on like 67 of views.py. 

Those I believe should have that settings file "autoloaded" in.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky still not working. The code:

```py
from mathics.settings import default_pymathics_modules
from mathics.core.definitions import Definitions
from mathics.core.evaluation import Evaluation

definitions = Definitions(add_builtin=True, extension_modules=default_pymathics_modules)
evaluation = Evaluation(definitions)

query = evaluation.parse("Settings`QuotedStrings")
quoted_strings = query.evaluate(evaluation).to_python()
print(quoted_strings)

query = evaluation.parse("Settings`$QuotedStrings")
quoted_strings = query.evaluate(evaluation).to_python()
print(quoted_strings)
```

**Comment by rocky** [comment]
I'll look at this when I get a chance. We probably also have something
nowadays to do both the parse and evaluate as one step. (Or should have
one.)

**Comment by rocky** [comment]
@TiagoCavalcanteTrindade 8cb023c has code to pick up from the settings whether to show quotes on the top-level string or not.

Please finish as you see fit. 

Also, I am finding the editorconfig value where we default to omitting newlines at the ends of files annoying. Github also seems to indicate that as well, in my opinion I would rather not see this all of the time. Would it be too disruptive to add the newlines at the end of the file?

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky I'll add the newlines.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky it still isn't working, I'll have time to fix it latter.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky it's ready to merge.

`Graphics3D`  isn't working, it returns `Exception raised: 'Graphics3DBox' object has no attribute 'boxes_to_js' Traceback (most recent call last)`. Maybe it be the same error than `PieChart`.

**Comment by rocky** [comment]
Thanks for finishing!

**Comment by rocky** [comment]
> @rocky it's ready to merge.
> 
> `Graphics3D` isn't working, it returns `Exception raised: 'Graphics3DBox' object has no attribute 'boxes_to_js' Traceback (most recent call last)`. Maybe it be the same error than `PieChart`.
> 
> (even in a older version of Mathics Django `Graphics3D` isn't working, maybe a problem in my clone or maybe a problem in rebasing Mathics Core)

I am not seeing this locally. What's the input, and what's full traceback?

**Comment by TiagoCavalcanteTrindade** [comment]
Input:
```wl
Graphics3D[Sphere[]]
```

Output:
```wl
System::exception:
Exception raised: 'Graphics3DBox' object has no attribute 'boxes_to_js' Traceback (most recent call last):  File "/home/tiago/mathics-django/mathics_django/web/views.py", line 245, in query result = evaluation.evaluate(expr, timeout=settings.TIMEOUT)  File "/home/tiago/.local/lib/python3.9/site-packages/mathics/core/evaluation.py", line 355, in evaluate result = run_with_timeout_and_stack(evaluate, timeout, self)  File "/home/tiago/.local/lib/python3.9/site-packages/mathics/core/evaluation.py", line 112, in run_with_timeout_and_stack return request()  File "/home/tiago/.local/lib/python3.9/site-packages/mathics/core/evaluation.py", line 348, in evaluate return self.format_output(self.last_eval, format)  File "/home/tiago/mathics-django/mathics_django/web/models.py", line 33, in <lambda> evaluation.format_output = lambda expr, format: format_output(evaluation, expr, format)  File "/home/tiago/mathics-django/mathics_django/web/format.py", line 100, in format_output return eval_boxes(result, result.boxes_to_js, obj) AttributeError: 'Graphics3DBox' object has no attribute 'boxes_to_js'</lambda>
```

**Comment by TiagoCavalcanteTrindade** [comment]
Also, @rocky another hint: in `drawGraphics3D` `data.axes.ticks_style` is undefined.

**Comment by rocky** [comment]
I am not seeing either problem. I think like before this be because you are pulling code from `"/home/tiago/.local/lib/python3.9/site-packages/mathics/core`  which may have old code.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky yes, was this. A `rm -rf` solved it.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky last but not least, the following isn't working:
```wl
LoadModule["pymathics.hello"]
PyMathics`Hello["World"]
```
The output:
image

I'm wanting to create a machine learning module, so I was starting from `pymathics-hello`...

**Comment by rocky** [comment]
@TiagoCavalcanteTrindade Things that still need fixing are

*  zoom on MathML (adding  a scrollbar onto a too-short window isn't useful)
mathjax

* Pie Charts
* Polygons (even if only a little bit better)
* Density plots (change need on Mathics Core). I will look at probably over the weekend)

I don't think we'll be in shape to release everything this weekend, so weekend after the upcoming one will probably be the earliest.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky the `PieChart` is working to me:
image

**Comment by rocky** [comment]
> @rocky the `PieChart` is working to me:
> image

No, this is wrong, for input `PieChart[{1, 4, 2}]`. Again, you didn't give input so it is impossible to say. (First rule of bug reporting: don't just give output, but also add the input). 

The SVG looks wrong, so I suspect this is something in Mathics core: 

```
<svg width="350.0px" height="350.0px" xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0.000000 0.000000 350.000000 350.000000">
                <ellipse cx="175.000000" cy="175.000000" rx="175.000000" ry="175.000000" style="stroke: rgb(0.000000%, 0.000000%, 0.000000%); stroke-opacity: 1.0; stroke-width: 0.666667px; fill: rgb(94.117647%, 64.705882%, 69.019608%); fill-opacity: 1.0; opacity: 1.0"></ellipse>
<ellipse cx="175.000000" cy="175.000000" rx="175.000000" ry="175.000000" style="stroke: rgb(0.000000%, 0.000000%, 0.000000%); stroke-opacity: 1.0; stroke-width: 0.666667px; fill: rgb(54.901961%, 52.156863%, 21.176471%); fill-opacity: 1.0; opacity: 1.0"></ellipse>
<ellipse cx="175.000000" cy="175.000000" rx="175.000000" ry="175.000000" style="stroke: rgb(0.000000%, 0.000000%, 0.000000%); stroke-opacity: 1.0; stroke-width: 0.666667px; fill: rgb(98.039216%, 81.568627%, 38.823529%); fill-opacity: 1.0; opacity: 1.0"></ellipse>
</svg>
```

I will compare with what I have in an older version.

**Comment by rocky** [comment]
> ```mathematica
> ```mathematica
> PyMathics`Hello["World"]
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

I will look at at fix over the weekend.

**Comment by rocky** [comment]
> @rocky last but not least, the following isn't working:
> 
> ```mathematica
> LoadModule["pymathics.hello"]
> PyMathics`Hello["World"]
> ```
> 
> The output:
> image
> 
> I'm wanting to create a machine learning module, so I was starting from `pymathics-hello`...

I just updated the code and put out a new release: https://pypi.org/project/pymathics-hello/ and https://github.com/mathics3/pymathics-hello/releases 

There is a lot that could be improved, but this is a small step forward.

**Pull request merged**
