### PR TITLE
Update mathics-threejs-backend to 1.0.0

### PR DESCRIPTION
**Pull request by TiagoCavalcante**

### CODE REVIEW

**Comment by TiagoCavalcante** [comment]
Seems that the Windows CI is outdated. That is looking for /bundle but I changed it in Makefile.

**Comment by rocky** [comment]
> Seems that the Windows CI is outdated. That is looking for /bundle but I changed it in Makefile.

So how do we fix this?

**Comment by TiagoCavalcante** [comment]
> So how do we fix this?

We merge. Then the CI is going to be updated in master.

**Review by rocky — APPROVED** [review]
Ok - let's try it!

**Comment by TiagoCavalcante** [comment]
My mistake: Windows workflow didn't use `make` (already happened with me the workflows be outdated). I pushed a fix.

**Pull request merged**
