### PR TITLE
Fix zoom problem

### PR DESCRIPTION
**Pull request by TiagoCavalcanteTrindade**
This branch fix the zoom problem and improve the line number calculating (too much lines for the text).

### CODE REVIEW

**Comment by rocky** [comment]
I am not seeing much of a difference (on Chrome or Firefox): 

zoom-colors
zoom-matrix

Also note that every other image in the list seems to drop out.

**Comment by rocky** [comment]
One more image to show that it is every other image (1st, 3rd, etc)
2x2-matrix

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky strange, I'll check this.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky it's the same in Firefox:
image

**Comment by rocky** [comment]
@TiagoCavalcanteTrindade And I get the boxed same results on Chrome, Firefox, and Opera. I tried refreshing several time.
Maybe you have a commit that hasn't been pushed?

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky I pushed some new modifications. I guess this should work now.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky in Firefox I'm also getting the error of the length (Microsoft Edge sometimes insist in not show errors).

**Comment by rocky** [comment]
AWESOME- LGTM!  Merge when you are feel ready. 

I see now extra commas in lists. I bet that has to do with Boxing information (like RowBox) that rightfully disappears but leaves around a remnant of its existence. 

But that is a separate problem. 

Overall I think the zoom feature great! Thanks!

**Comment by TiagoCavalcanteTrindade** [comment]
> I see now extra commas in lists. I bet that has to do with Boxing information (like RowBox) that rightfully disappears but leaves around a remnant of its existence.

@rocky some of the colors that should appear aren't anymore. When all old code be replace these things will stop happening, but by now I'll fix it.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky this was a good bug 😆, while solving it I solved other one [that only happened in Microsoft Edge] which did the colors in the list be in different heights.

**Comment by rocky** [comment]
@TiagoCavalcanteTrindade  With the latest changes even more awesome, difficult as that is to imagine!

I had been really depressed before this work, that we (well, okay, mostly you) had spent all of this time upgrading releases, rewriting code, cleaning up code yet _still_ there were all of these little bugs. 

I am finally seeing the light at the end of the tunnel, and am pleased beyond my ability to express myself, that we finally have someone can at least get the Javascript side under control and therefore be in a good position to advise use as to how to get the whole API interface more sane and sensible. 

Again, thanks!

(And let's merge this - unless you still have trepidation)

**Pull request merged**
