### PR TITLE
Add Cylinders

### PR DESCRIPTION
**Pull request by rocky**
The version of Three.js appeently supports Cylinders. 

Something else in the back of my mind is to start incrementing Three.js until we get to an incompatibility.

Feel free to make commits on top of this.

### CODE REVIEW

**Comment by rocky** [comment]
I am seeing a problem with Asymptote formatting of cyclinders where the bounding box starts below the base of the cylinder. However I can't figure out how to fix this. @mmatera if you can, let's fix. Otherwise let's skip.

**Comment by rocky** [comment]
Cylinders needs to have an orientation parameter.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky the current version of three.js support cylinders, but I didn't found them in the documentation.

**Comment by rocky** [comment]
> 
> 
> @rocky the current version of three.js support cylinders, but I didn't found them in the documentation.


Maybe https://threejs.org/docs/#api/en/geometries/CylinderGeometry ? 

Other objects we are missing are [Tube](https://reference.wolfram.com/language/ref/Tube.html), and [Cone](https://reference.wolfram.com/language/ref/Cone.html) is those happen to be documented. 

But personally I think https://github.com/Mathics3/mathics-django/issues/66 would have the most impact of the many things we are missing.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky, I mean in the Django documentation of Mathics.

I'll look at #66 in a few hours, also busy now.

And in the last hours I was working in draw polygons with other coplanar planes other than z. Any idea on how to that, I'll push my branch now and then go back to studies.

**Comment by rocky** [comment]
> 
> 
> @rocky, I mean in the Django documentation of Mathics.

In general since we are trying to be compatible with Mathematica see https://reference.wolfram.com/language/ref/Polygon.html

> 
> I'll look at #66 in a few hours, also busy now.
> 
> And in the last hours I was working in draw polygons with other coplanar planes other than z. Any idea on how to that, I'll push my branch now and then go back to studies.

It looks like we need to implement [CoplanarPoints](https://reference.wolfram.com/language/ref/CoplanarPoints.html) in Mathics. I added a [Mathics issue](https://github.com/mathics/Mathics/issues/1416) for that. 

For now though, I'd assume that it is the users burden to make sure the points lie in the plain.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky I'm wanting to implement the following:
- [Arrow](https://reference.wolfram.com/language/ref/Arrow.html)
- [Cone](https://reference.wolfram.com/language/ref/Cone.html)
- [Cylinder](https://reference.wolfram.com/language/ref/Cylinder.html)
- [Dodecahedron](https://reference.wolfram.com/language/ref/Dodecahedron.html)
- [Octahedron](https://reference.wolfram.com/language/ref/Octahedron.html)
- [Tetrahedron](https://reference.wolfram.com/language/ref/Tetrahedron.html)

The arrow can be done with the help of three.js' `ArrowHelper`.

All the others have a respective geometry in three.js.

`Cylinder` need to be rotated, and it [probably] can be done by a translate of the subtraction of the center and tip.

The current branch of Mathics Core is giving me the following error when I try to draw a cylinder:
```wl
System::exception:
Exception raised:  Traceback (most recent call last):  File "/home/tiago/mathics-django/mathics_django/web/views.py", line 245, in query result = evaluation.evaluate(expr, timeout=settings.TIMEOUT)  File "/usr/lib/python3.9/site-packages/Mathics3-2.2.1.dev0-py3.9.egg/mathics/core/evaluation.py", line 355, in evaluate result = run_with_timeout_and_stack(evaluate, timeout, self)  File "/usr/lib/python3.9/site-packages/Mathics3-2.2.1.dev0-py3.9.egg/mathics/core/evaluation.py", line 112, in run_with_timeout_and_stack return request()  File "/usr/lib/python3.9/site-packages/Mathics3-2.2.1.dev0-py3.9.egg/mathics/core/evaluation.py", line 348, in evaluate return self.format_output(self.last_eval, format)  File "/home/tiago/mathics-django/mathics_django/web/models.py", line 33, in <lambda> evaluation.format_output = lambda expr, format: format_output(evaluation, expr, format)  File "/home/tiago/mathics-django/mathics_django/web/format.py", line 100, in format_output return eval_boxes(result, result.boxes_to_js, obj)  File "/home/tiago/mathics-django/mathics_django/web/format.py", line 28, in eval_boxes boxes = fn(evaluation=obj, **options)  File "/usr/lib/python3.9/site-packages/Mathics3-2.2.1.dev0-py3.9.egg/mathics/builtin/drawing/graphics3d.py", line 464, in boxes_to_js json_repr = self.boxes_to_json(leaves, **options)  File "/usr/lib/python3.9/site-packages/Mathics3-2.2.1.dev0-py3.9.egg/mathics/builtin/drawing/graphics3d.py", line 485, in boxes_to_json ) = self._prepare_elements(leaves, options)  File "/usr/lib/python3.9/site-packages/Mathics3-2.2.1.dev0-py3.9.egg/mathics/builtin/drawing/graphics3d.py", line 351, in _prepare_elements elements = Graphics3DElements(leaves[0], evaluation)  File "/usr/lib/python3.9/site-packages/Mathics3-2.2.1.dev0-py3.9.egg/mathics/builtin/drawing/graphics3d.py", line 851, in __init__ super(Graphics3DElements, self).__init__(content, evaluation)  File "/usr/lib/python3.9/site-packages/Mathics3-2.2.1.dev0-py3.9.egg/mathics/builtin/graphics.py", line 2425, in __init__ self.elements = list(convert(content, self.get_style_class()(self)))  File "/usr/lib/python3.9/site-packages/Mathics3-2.2.1.dev0-py3.9.egg/mathics/builtin/graphics.py", line 2423, in convert raise BoxConstructError mathics.builtin.base.BoxConstructError</lambda>
```

About the zoom, I'm thinking in it. The problem is the following: when the formula is too long we need a scrollbar (just 1) because of the problem of MathJax doesn't respect the margin, but when we zoom, we want a scrollbar just at the zoomed formula (we want it overflow to be visible). An approach to solve this [maybe] is calculate the breaking formula width and re-calculating it on every resize. I'll try this approach.

**Comment by rocky** [comment]
> @rocky I'm wanting to implement the following:
> 
> * [Arrow](https://reference.wolfram.com/language/ref/Arrow.html)
> * [Cone](https://reference.wolfram.com/language/ref/Cone.html)
> * [Cylinder](https://reference.wolfram.com/language/ref/Cylinder.html)
> * [Dodecahedron](https://reference.wolfram.com/language/ref/Dodecahedron.html)
> * [Octahedron](https://reference.wolfram.com/language/ref/Octahedron.html)
> * [Tetrahedron](https://reference.wolfram.com/language/ref/Tetrahedron.html)
> 
> The arrow can be done with the help of three.js' `ArrowHelper`.
> 
> All the others have a respective geometry in three.js.
> 

Awesome! 

> `Cylinder` need to be rotated, and it [probably] can be done by a translate of the subtraction of the center and tip.
> 

There was a branch that started implementing Transform inside Mathics Core if that'd be useful. See https://github.com/mathics/Mathics/blob/0a283aa975225d2c6ed04b09feab3d219ec4774c/mathics/builtin/graphics.py#L309-L435

The code can't be merged in as is because it pulls in other dependencies and this code reflects the thinking that it is cool to have 4.6K python code including built-in primitives, boxing of the primitives and formatting this into different formats all in one file. 

> The current branch of Mathics Core is giving me the following error when I try to draw a cylinder:
> 
> ```mathematica
> System::exception:
> Exception raised:  Traceback (most recent call last):  File "/home/tiago/mathics-django/mathics_django/web/views.py", line 245, in query result = evaluation.evaluate(expr, timeout=settings.TIMEOUT)  File "/usr/lib/python3.9/site-packages/Mathics3-2.2.1.dev0-py3.9.egg/mathics/core/evaluation.py", line 355, in evaluate result = run_with_timeout_and_stack(evaluate, timeout, self)  File "/usr/lib/python3.9/site-packages/Mathics3-2.2.1.dev0-py3.9.egg/mathics/core/evaluation.py", line 112, in run_with_timeout_and_stack return request()  File "/usr/lib/python3.9/site-packages/Mathics3-2.2.1.dev0-py3.9.egg/mathics/core/evaluation.py", line 348, in evaluate return self.format_output(self.last_eval, format)  File "/home/tiago/mathics-django/mathics_django/web/models.py", line 33, in <lambda> evaluation.format_output = lambda expr, format: format_output(evaluation, expr, format)  File "/home/tiago/mathics-django/mathics_django/web/format.py", line 100, in format_output return eval_boxes(result, result.boxes_to_js, obj)  File "/home/tiago/mathics-django/mathics_django/web/format.py", line 28, in eval_boxes boxes = fn(evaluation=obj, **options)  File "/usr/lib/python3.9/site-packages/Mathics3-2.2.1.dev0-py3.9.egg/mathics/builtin/drawing/graphics3d.py", line 464, in boxes_to_js json_repr = self.boxes_to_json(leaves, **options)  File "/usr/lib/python3.9/site-packages/Mathics3-2.2.1.dev0-py3.9.egg/mathics/builtin/drawing/graphics3d.py", line 485, in boxes_to_json ) = self._prepare_elements(leaves, options)  File "/usr/lib/python3.9/site-packages/Mathics3-2.2.1.dev0-py3.9.egg/mathics/builtin/drawing/graphics3d.py", line 351, in _prepare_elements elements = Graphics3DElements(leaves[0], evaluation)  File "/usr/lib/python3.9/site-packages/Mathics3-2.2.1.dev0-py3.9.egg/mathics/builtin/drawing/graphics3d.py", line 851, in __init__ super(Graphics3DElements, self).__init__(content, evaluation)  File "/usr/lib/python3.9/site-packages/Mathics3-2.2.1.dev0-py3.9.egg/mathics/builtin/graphics.py", line 2425, in __init__ self.elements = list(convert(content, self.get_style_class()(self)))  File "/usr/lib/python3.9/site-packages/Mathics3-2.2.1.dev0-py3.9.egg/mathics/builtin/graphics.py", line 2423, in convert raise BoxConstructError mathics.builtin.base.BoxConstructError</lambda>
> ```
> 

You keep pasting traceback (as one line line) which is output. And then want me to figure out what input you gave. 

The master branch doesn't have Cyclinder. This branch can't be merged into master as is - there are merge conflicts. 


> About the zoom, I'm thinking in it. The problem is the following: when the formula is too long we need a scrollbar (just 1) because of the problem of MathJax doesn't respect the margin, but when we zoom, we want a scrollbar just at the zoomed formula (we want it overflow to be visible). An approach to solve this [maybe] is calculate the breaking formula width and re-calculating it on every resize. I'll try this approach.

**Comment by TiagoCavalcanteTrindade** [comment]
> You keep pasting traceback (as one line line) which is output. And then want me to figure out what input you gave.

@rocky sorry. This output is the same for the following inputs:
```wl
Graphics3D[Cylinder[]]
Graphics3D[Cylinder[{0,0,0},{1,1,1}}]]
```

**Comment by rocky** [comment]
> > You keep pasting traceback (as one line line) which is output. And then want me to figure out what input you gave.
> 
> @rocky sorry. This output is the same for the following inputs:
> 
> ```mathematica
> Graphics3D[Cylinder[]]
> Graphics3D[Cylinder[{0,0,0},{1,1,1}}]]
> ```
> 
> Also, I'll start breaking the output into multiple lines.
> 
> > > @rocky I'm wanting to implement the following:
> > > 
> > > * [Arrow](https://reference.wolfram.com/language/ref/Arrow.html)
> > > * [Cone](https://reference.wolfram.com/language/ref/Cone.html)
> > > * [Cylinder](https://reference.wolfram.com/language/ref/Cylinder.html)
> > > * [Dodecahedron](https://reference.wolfram.com/language/ref/Dodecahedron.html)
> > > * [Octahedron](https://reference.wolfram.com/language/ref/Octahedron.html)
> > > * [Tetrahedron](https://reference.wolfram.com/language/ref/Tetrahedron.html)
> > > 
> > > The arrow can be done with the help of three.js' `ArrowHelper`.
> > > All the others have a respective geometry in three.js.
> > 
> > 
> > Awesome!
> 
> Can you implement them in Mathics Core?

I'll try to look at Arrow since that seems the easiest, but after other breakage has been fixed, like finishing piechart, at least understanding what's up with the graphics in lists, and getting densityplot going. 

As is my custom over the weekend I put will try to put out another docker image. I'm a little concerned that the ones recently could be seen as a regression because things that used to work no longer do.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky doing it I saw that the Mathics' Cylinder class (which now I understand 😄) is different from WL's one. It's following the three.js cylinder geometry, but with a bit of math (just calculate the mean and double the radius to get the height) we can follow the WL function. What do you think?

**Comment by rocky** [comment]
@TiagoCavalcanteTrindade - yes that is my understanding too. The question I have is whether the math should be done on the Mathics side (that is assume that most programs that render cylinders will _not_ be able to take the spec and do the math) or whether it should  be done on the Javascript/three.js side. 

Historically the code was developed to want to put all the calculation into Mathics core. The problem with that is that the core can bind in decisions that make it hard for the front end to undo. For example if core decides to take vector graphics and rasterize this, then front ends have to work with raster images which may be more cumbersome, more data, and give poorer end results. 

Another example is that we just fixed but in a non-general way was allowing the front-end to get SVGs without embedding in MathML (which many times is not needed or desired). Trying to parse and strip out MathML and the decoding a base64 encoded SVG is more work, and fragile and just plain silly.

I am now of the opinion that if we can just describe what's up in JSON and ship that across the all the to_svg that is done in core can be put in some sort pymathics (or in the case fo Mathics-Django we don't even need that you can just extend mathics.js)

The code for converting JSON into svg shouldn't be any more work conceptually than going from the Mathics Lists to svg.

Your thoughts?

**Comment by TiagoCavalcanteTrindade** [comment]
> @TiagoCavalcanteTrindade - yes that is my understanding too. The question I have is whether the math should be done on the Mathics side (that is assume that most programs that render cylinders will not be able to take the spec and do the math) or whether it should be done on the Javascript/three.js side.

@rocky I guess we shouldn't fold the data in the backend assuming one specific frontend, if in the front end we need the data as it was we would need to undo what Mathics Core made, twice the work.

> I am now of the opinion that if we can just describe what's up in JSON and ship that across the front end, then the all the to_svg that is done in core can be put in some sort pymathics (or in the case fo Mathics-Django we don't even need that -- you can just extend mathics.js)I am now of the opinion that if we can just describe what's up in JSON and ship that across the front end, then the all the to_svg that is done in core can be put in some sort pymathics (or in the case fo Mathics-Django we don't even need that -- you can just extend mathics.js)

Yes, a JSON array would be good for it, the work will be the same, and in a frontend that don't support SVGs we won't need to do some craziness to convert it to the expected format.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky I also think we should extend the behavior of WL and allow multiple cylinders to be drawn at once.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky when the number of points is odd, what is the expected behavior? `raise BoxConstructError`, a message, or the function be undefined (`Cylinder[positions_?(EvenQ[Length[#]] &)]`)?

**Comment by rocky** [comment]
> @rocky when the number of points is odd, what is the expected behavior? `raise BoxConstructError`, a message, or the function be undefined (`Cylinder[positions_?(EvenQ[Length[#]] &)]`)?

I'd follow whatever Mathematica does. But I don't know what that is. @mmatera  ?

**Comment by mmatera** [comment]
This is the behaviour in WMA 11.0.3


```
Graphics3D[{Cylinder[{{0,0,0},{0,0,1}},{.1}]}]
```

image



```
Graphics3D[{Cylinder[{{0,0,0},{0,0,1},{1,0,0}},{.1,.2}]}]
```
image

```
Graphics3D[{Cylinder[{{0,0,0},{0,0,1},{1,0,0},{1,0,1}},{.1,.2}]}]
```
image

```
Graphics3D[{Cylinder[{{{0,0,0},{0,0,1}},{{1,0,0},{1,0,1}}},{.1,.2}]}]
```
image

**Comment by mmatera** [comment]
So, this is how it works:
* If you pass a list of two points, and a single radius, it draws it with the center of the limiting circles in the specified coordinates 
* if you want more than one cylinder, you must pass a list of lists. Each element of that list can consist of a list of one or two sets of coordinates. 
* In any case, a wrong argument does not send an error message: it just draws what it can, and puts a pink background.

**Comment by TiagoCavalcanteTrindade** [comment]
@mmatera thanks, I'll try to let `Cylinder` closer to WMA. I just think that warning are good to the user know that something is wrong, but I guess draw it anyway

**Comment by mmatera** [comment]
@TiagoCavalcanteTrindade, the warning should be there. The point is when it should be raised. 
```
Cilynder[{{0,0,0},{1,1,1},{1,2,1},{3,2,1}}]
 ```
has an even number of coordinated, but still is wrong. It should be: 
```
Cilynder[{{{0,0,0},{1,1,1}},{{1,2,1},{3,2,1}} }]
 ```

**Comment by TiagoCavalcanteTrindade** [comment]
@mmatera I implemented `Cylinder` in a different manner, it currently accepts the points like `Sphere` does, in a list, not a list of lists. My intention is to change that.

**Pull request closed without merging**
