### PR TITLE
Start removing Prototype and Scriptaculous

### PR DESCRIPTION
**Pull request by TiagoCavalcanteTrindade**
@rocky it isn't complete but I think is better merge before we do too much changes in master.

### CODE REVIEW

**Review by rocky — COMMENTED** [review]
If this happens the dropdowns stop working. 

Recently, I noticed that even before this, some of the buttons have stopped working. If I run open worksheet (the leftmost icon) and and I enter "Cancel", the menu no longer appears.

Probably we should undo the removals previously done or fix this up in some other way. 

In my opinion right now this kind of thing isn't the as important as improving polygon or getting density plot going.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky I'll fix these things. I forget to test these ones in last time I modified, but this gonna be easy to fix.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky now the input area is fixed.

The cancel button I guess was a problem while rebasing (in my computer), now it's also fixed.

---

> In my opinion right now this kind of thing isn't the as important as improving polygon or getting density plot going.

I also think now, but when I started doing it there were less things to do. This is why I said to merge before it be finished, because of it'll take time to I work in it again.

**Comment by rocky** [comment]
> @rocky now the input area is fixed.
>

When I tried the input area is now broken and I can't enter input. The "=" on the right-hand side is in a different font and doesn't work. And Ctrl-enter (the alternate way of entering input) also doesn't evaluate the text that is on input.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky fixing it now.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky I reverted to an older version of my code.

I already tested the following:
- open, delete and save worksheets;
- global keys (Ctrl+D, Ctrl+O, Ctrl+S);
- popup's yes and no buttons (and its keyboard versions);
- documentation;

**Comment by rocky** [comment]
@TiagoCavalcanteTrindade  I tested everything and things look good. There even seems to be a slight improvement in the text area in being able to resize that. 

Believe me, I know how frustrating it is to work with this code and trying to improve it only to find there is an additional mess that needs attending. And then having to back off on more ambitious changes because of one of these newly discovered "gotcha"s that prevent progress. 

We just came across one in the way density plots are handled. 

I am optimistic that eventually all of this will be sorted out.

**Comment by rocky** [comment]
There is a slight misfeature in that if you try to save a worksheet without giving it a name it appears to "save" it and then blanks out the save and cancel button. I don't think this happened before.

However, nothing appears to be saved. And this is not such a big deal that it needs to be fixed with any urgency. I'm just noting. (We should probably open an issue, but it is just a low priority one for me.)

**Pull request merged**
