### PR TITLE
Replace `graphics3d.js` by mathics-threejs-backend

### PR DESCRIPTION
**Pull request by TiagoCavalcanteTrindade**

### CODE REVIEW

**Comment by rocky** [comment]
Love the speed improvements!  

Why does the bounding box in cylinder example in the gallery appear smaller than in the other examples?

**Comment by TiagoCavalcanteTrindade** [comment]
Not just this looks smaller, but other examples too, the extent calculation and camera position scaling are still not perfect. I'll fix this in another mathics-threejs-backend release.

**Review by rocky — APPROVED** [review]
LGTM - but we'll keep going on in future PRs to do more....

**Comment by rocky** [comment]
@TiagoCavalcanteTrindade I am not seeing any graphics3js output with this now. Reverting until we can figure out what's up.

**Pull request merged**
