### PR TITLE
Remove more Prototype and fix some bugs

### PR DESCRIPTION
**Pull request by TiagoCavalcanteTrindade**
Now to remove ALL Prototype and Scriptaculous we just need to create our own sortable list!

### CODE REVIEW

**Comment by rocky** [comment]
> Now to remove ALL Prototype and Scriptaculous we just need to create our own sortable list!

I guess this means there is more work to be done?  Here or in another PR? 

Also, you mention having fixed some bugs. What bugs were these? 

Inquiring minds want to know!

Have you considered how one would test any of the code?

**Comment by TiagoCavalcanteTrindade** [comment]
> I guess this means there is more work to be done? Here or in another PR?

To say the truth I'm anxious to move `graphics3d.js` to graphics3d.js (move to its own library), so I guess another PR.

> Also, you mention having fixed some bugs. What bugs were these?
>
> Inquiring minds want to know!

Before this, when you delete a worksheet the popup still appears, but with a blank body.

> Have you considered how one would test any of the code?

Saving, opening, deleting worksheets; creating, evaluating, deleting a cell; and searching in the documentation.

**Comment by rocky** [comment]
> 
> 
> > I guess this means there is more work to be done? Here or in another PR?
> 
> To say the truth I'm anxious to move `graphics3d.js` to graphics3d.js (move to its own library), so I guess another PR.


Ok. You are the expert in this area, so merge whenever you feel it best. 
> 
> > Also, you mention having fixed some bugs. What bugs were these?
> > Inquiring minds want to know!
> 
> Before this, when you delete a worksheet the popup still appears, but with a blank body.
> 
> > Have you considered how one would test any of the code?
> 
> Saving, opening, deleting worksheets; creating, evaluating, deleting a cell; and searching in the documentation.

Ok. But I meant have you considered testing in an automated way?

**Comment by TiagoCavalcanteTrindade** [comment]
> Ok. But I meant have you considered testing in an automated way?

@rocky front-end testing is something I have never done. Anyway, that's a great idea, test it again and again and again is very boring. I'll give it a look after finish the other (3?) things on my list.

**Review by rocky — APPROVED** [review]
LGTM

**Pull request merged**
